spring:
  application:
    name: academia-api

  datasource:
    url: 'jdbc:mysql://db-br-sp-1.danka.tech:13306/lily_36962a6e1e5cf75e'
    username: misty_7abf4efde42e1dae
    password: 8ce1c530252fbc1033728f1586a26ce2
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    database: MYSQL

  sql:
    init:
      mode: never

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        metrics: /metrics
      exposure:
        include: 'health,metrics'
  endpoint:
    metrics:
      access: read-only
    health:
      access: read-only
      show-details: always

logging:
  level:
    '[org.springframework.security]': error
